feat: :sparkles: added new controllers, env,  route updates, refactor connection strem
adobki/SchoolPilot pull request #8
Opened 2024-01-03 18:55 UTC by Yusuf-R

​
## Description

StudentController for sign-in, activateProfile and login
Authentication Controller for Basic Authentication using tokens
Implemented connection stream for Redis and MongoDB client using .env file
​
## Related Issue

​
## Motivation and Context

​
## How Has This Been Tested?

​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-01-03 23:46 UTC, Dev-wonderful commented on src/routes/index.js
I think you should move the student router to a different file then import it into this index file with the name `studentRoute` then use `router.use()` to point to the `studentRoute` handler, almost like blueprint in flask

In the `routes/student.js` file
```
const express = require('express');
const studentRouter = express.Router()

studentRouter.post('/signin', studentController.activateProfile);

and so on
```

in the `routes/index.js` file
```
const { studentRouter } = require('path/to/routes/student.js');
const express = require('express');
const router = express.Router();

router.use('/api/v1/studentportal', studenRouter);

and so on
```

You can check for the credibility of this approach, this way this file won't get too cluttered

2024-01-04 06:13 UTC, Yusuf-R commented on src/routes/index.js
Okay, that's nice, will refactor

2024-01-04 08:43 UTC, adobki requested changes
Good job, bro! All or at least some of these need to be addressed before this is approved though, so that a separate PR won't need to be created just for them. Thanks.

2024-01-04 08:43 UTC, adobki commented on src/controllers/StudentsController.js
> +      await dbClient.isAlive();
As discussed, you need to test/use the return value of this expression, as nothing after this line would work if it is falsey. Remember that the logic we implemented in the `isAlive` method actually catches/handles all its errors, so your try/catch statement here would never actually have any errors to catch from same. A false is simply returned instead.

2024-01-04 08:43 UTC, adobki commented on src/controllers/StudentsController.js
> +      if (user.status !== statuses[1]) {
This line should be `if (user.status === statuses[0]) {`, as verification is for status[0] only, right?

2024-01-04 08:43 UTC, adobki commented on src/routes/index.js
> . . .will refactor

Waiting for this before approving the PR. . . @Yusuf-R

2024-01-04 08:43 UTC, adobki commented on src/routes/index.js
>  const userController = require('../controllers/UsersController');
Remember to delete this and the referenced controller.

2024-01-04 08:43 UTC, adobki commented on src/controllers/StudentsController.js
> +const dbClient = require('../utils/db');
I think you should import `dbClient` from the `base` model, as opposed to directly from the `db` util.

2024-01-04 08:43 UTC, adobki commented on src/controllers/StudentsController.js
> +      await dbClient.isAlive();
Same as above, but in this case, you should probably just take out the try/catch altogether and simply use an if statement.

2024-01-04 08:43 UTC, adobki commented on src/controllers/StudentsController.js
> +      await dbClient.isAlive();
Same as above, . . .use an if statement. . .

2024-01-04 08:43 UTC, adobki commented on src/controllers/AuthController.js
> +      await redisClient.set(key, userID, EXP);
All `redisClient` calls should be preceeded by an `isAlive` call in the same block/scope, yeah? Just wondering. . .

2024-01-04 10:42 UTC, Yusuf-R commented on src/controllers/StudentsController.js
> +      if (user.status !== statuses[1]) {
At this stage, it is login, we believe the user status should now be active and not at the init stage, thus preventing a user at init stage from login in directly

2024-01-04 11:14 UTC, Yusuf-R commented on src/controllers/AuthController.js
> +      await redisClient.set(key, userID, EXP);
I implemented the isAlive check for set, get and del in the methods for the Redis class. 
thus not needing a preceding check

2024-01-04 16:14 UTC, Yusuf-R commented on src/controllers/StudentsController.js
> +      await dbClient.isAlive();
code updated

2024-01-04 16:14 UTC, Yusuf-R commented on src/routes/index.js
>  const userController = require('../controllers/UsersController');
folder structure updated

2024-01-04 16:16 UTC, Yusuf-R commented on src/controllers/StudentsController.js
> +const dbClient = require('../utils/db');
it's the utility folder

2024-01-04 16:16 UTC, Yusuf-R commented on src/controllers/StudentsController.js
> +      await dbClient.isAlive();
updated

2024-01-04 16:16 UTC, Yusuf-R commented on src/controllers/StudentsController.js
> +      await dbClient.isAlive();
updated

2024-01-04 16:18 UTC, Yusuf-R commented on src/routes/index.js
Done

2024-01-08 06:19 UTC, adobki approved these changes

2024-01-08 06:20 UTC, merged